# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksissued',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
